variables:
  IMAGE_NAME: muhammadrz/go-sys
  IMAGE_TAG: gosys-app-1.0

stages:
  - test
  - build

run_tests:
  stage: test
  image: golang:latest
  before_script:
    - go mod tidy
  script:
    - go test -v

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG